# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: happyshop
  pool: 5
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: happyshop
  pool: 5
  username: postgres
  password: 

production:
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
