# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: happyshop
  pool: 5
  username: postgres
  password: vu6RefrA

test:
  adapter: postgresql
  encoding: unicode
  database: happyshop
  pool: 5
  username: postgres
  password: vu6RefrA

production:
  adapter: postgresql
  encoding: unicode
  database: happyshop
  pool: 5
  username: postgres
  password: vu6RefrA
